/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sstan' at '23/11/16 5:02 PM' with Gradle 3.1
 *
 * @author sstan, @date 23/11/16 5:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
